global:
  scrape_interval: 10s

scrape_configs:
  - job_name: 'consumer_job'
    metrics_path: '/metrics'
    static_configs:s
      - targets: ['consumer-service:4000']
  - job_name: 'producer_job'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['producer-service:4000']