global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'Sender'
    static_configs:
      - targets: ['host.docker.internal:51111']

  - job_name: 'Receiver'
    static_configs:
      - targets: ['host.docker.internal:52222']